<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CouponCodeInputField</name>
   <tag></tag>
   <elementGuidId>05ed4125-98ef-4309-9dca-7e75cc4d4e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Coupon code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a81d03d-b3e9-47cd-b2cd-81df32be59bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51d1a126-c7f3-4ff2-a567-ed8bbefe1e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>329e1696-0b5d-49a4-a977-7c4e84572755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>3f232e00-6e94-4e01-b4d9-10e1b4344a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_code</value>
      <webElementGuid>2265a12a-5abb-4061-811e-ed02561bc8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Coupon code</value>
      <webElementGuid>1dd2010f-a8d0-444e-aa73-45ab3f64c67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_code&quot;)</value>
      <webElementGuid>b9faf6d8-96ed-41f6-8b1d-d28156dda33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon_code']</value>
      <webElementGuid>5647de43-f41e-44d0-8397-c3f1083a090c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/div/div/form/table/tbody/tr[2]/td/div/input</value>
      <webElementGuid>45b70672-ffae-4fd7-93b7-bbff11327c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/input</value>
      <webElementGuid>3370def2-926b-4279-9925-7f6b4171a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'coupon_code' and @id = 'coupon_code' and @placeholder = 'Coupon code']</value>
      <webElementGuid>79f95d9c-a48d-4258-bbb2-052551453cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
