<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuantityDownButton</name>
   <tag></tag>
   <elementGuidId>73850dac-e345-4a5e-8a3d-632ad8b641f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_67e0e179800d5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity_67e0e179800d5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Flying Ninja quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9e55a69-76af-4012-ab1a-e40a3e8bf5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>be0a49d5-079c-4b83-ac3a-7a9be7629e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_67e0e179800d5</value>
      <webElementGuid>fb8d37c8-ee57-40e3-9960-cf38f91f7e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>27000997-51e0-4434-a6a3-07e149cb0282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a415fc02-a183-4bf3-b55d-2a5e7b048515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bdb7ec41-207f-4630-9b69-ffbd80492a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[a684eceee76fc522773286a895bc8436][qty]</value>
      <webElementGuid>1ec140a1-0510-42c7-93cb-98bedb934ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>56ced748-32ac-441a-b177-9e8aba29fd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>064dfcc1-60f9-496a-9a72-b63c017d3dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>105e3638-3eff-4c0f-b3f0-d6661b469c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>17574458-8d83-42d0-9645-cb263fcba61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_67e0e179800d5&quot;)</value>
      <webElementGuid>8e3b5d0d-7a2e-477f-8ccc-1d22f374b5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_67e0e179800d5']</value>
      <webElementGuid>8795e958-fa75-4a9a-9d4d-5a313eb61aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/div/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>941429df-1bdd-47fd-90d1-3498dd9bb745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0d96fcc6-fe4e-48ce-92ef-5e7c0a0f49f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_67e0e179800d5' and @name = 'cart[a684eceee76fc522773286a895bc8436][qty]' and @title = 'Qty']</value>
      <webElementGuid>c7d55c4e-1e5c-4514-919e-a84a4061005b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
