<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuantityUpButton</name>
   <tag></tag>
   <elementGuidId>c8a46671-8f3c-4b3f-b2a2-f4d8784c8ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.quantity-button.quantity-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='quantity-button quantity-up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Happy Ninja quantity Add to cart&quot;i >> div >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bee0f4ee-7aba-4818-b4b9-001f1248a1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity-button quantity-up</value>
      <webElementGuid>7d301a76-db91-4a03-ba71-1cb73ba69f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-26&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;cart&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;quantity-nav&quot;]/div[@class=&quot;quantity-button quantity-up&quot;]</value>
      <webElementGuid>0ef3e480-70cd-4f68-b214-dbc04f7ec540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-26']/div[2]/form/div/div/div</value>
      <webElementGuid>0b306dbb-a0c1-47bc-8f83-4dd6dca1cb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>c31622ea-8e24-44c8-bc11-f48ee4867764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
