<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuantityDownButton</name>
   <tag></tag>
   <elementGuidId>25b3f5cd-c215-4872-91b9-e623a2d4f32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.quantity-button.quantity-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='quantity-button quantity-down']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Happy Ninja quantity Add to cart&quot;i >> div >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1471f8b7-92fe-4a6d-a98e-720c85406fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity-button quantity-down</value>
      <webElementGuid>2ca75d48-8d65-4352-97ec-bef5f3922ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-26&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;cart&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;quantity-nav&quot;]/div[@class=&quot;quantity-button quantity-down&quot;]</value>
      <webElementGuid>ab364512-aff0-4986-8089-9361e62e3cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-26']/div[2]/form/div/div/div[2]</value>
      <webElementGuid>85594e66-5648-48e9-a292-84da3e23b73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
      <webElementGuid>662a8d66-dee7-42f4-8587-4a0d550c5e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
