<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReviewSection</name>
   <tag></tag>
   <elementGuidId>31dfed56-dc9d-43e5-940b-6e925223cf84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-noreviews</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comments']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;There are no reviews yet.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bcd9a558-0b4a-49f2-b712-9e6f19528b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-noreviews</value>
      <webElementGuid>a2a4c5fd-dcd8-45eb-aa94-d43377d3563e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>There are no reviews yet.</value>
      <webElementGuid>26845865-e52d-4236-8657-aed9d47b1809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comments&quot;)/p[@class=&quot;woocommerce-noreviews&quot;]</value>
      <webElementGuid>7eb1369f-9582-421f-83ce-dfbae3284f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments']/p</value>
      <webElementGuid>cb896d6b-5cbb-438c-8d36-4a74a15e1445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::p[1]</value>
      <webElementGuid>44917abc-0c6c-4959-adb1-4632c032036c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::p[2]</value>
      <webElementGuid>29a707d0-b122-42db-bfc8-43404d8b08c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You may also like…'])[1]/preceding::p[1]</value>
      <webElementGuid>727dc866-4a90-478f-a70f-0b374e9e6272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[2]/preceding::p[1]</value>
      <webElementGuid>74ed8e1f-9a6c-413c-b62c-718f41b38b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='There are no reviews yet.']/parent::*</value>
      <webElementGuid>696d8f75-cba1-4f21-8eee-e100f994e913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/p</value>
      <webElementGuid>e19f652d-64ea-46a2-b42f-a4d681734330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'There are no reviews yet.' or . = 'There are no reviews yet.')]</value>
      <webElementGuid>8f4358f9-3463-470b-8966-c43608cbebf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
