<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyAccountDesc</name>
   <tag></tag>
   <elementGuidId>3cfbdb78-f959-4478-a256-53870b0e0063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-MyAccount-content > p:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;woocommerce-MyAccount-content&quot;]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;From your account dashboard you can view your recent orders, manage your shippin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9eb02c2f-7c5f-4308-9806-d7459c7351c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From your account dashboard you can view your recent orders, manage your shipping and billing addresses, and edit your password and account details.</value>
      <webElementGuid>e4029415-5edc-454a-b04e-bbd918bf639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-10&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/p[2]</value>
      <webElementGuid>cbee493d-ca48-4eb9-a021-4e99222095fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-10']/div/div/div/p[2]</value>
      <webElementGuid>e7031b5d-8835-4ff2-b15c-ed6ae1d61a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::p[1]</value>
      <webElementGuid>3db89d52-303c-4842-9bf6-cbf636aa881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KatalonLover'])[2]/following::p[1]</value>
      <webElementGuid>4cda9f7c-14b4-4ed1-b9f6-dd91356c05d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='From your account dashboard you can view your']/parent::*</value>
      <webElementGuid>1a3cd176-043a-4052-9cb9-7d4f7745389c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p[2]</value>
      <webElementGuid>f1dd4a51-d5d5-47cb-aae8-4f8f1be78ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'From your account dashboard you can view your recent orders, manage your shipping and billing addresses, and edit your password and account details.' or . = 'From your account dashboard you can view your recent orders, manage your shipping and billing addresses, and edit your password and account details.')]</value>
      <webElementGuid>74239388-8f3f-4368-9b0f-6351ec647798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
