<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingEmail</name>
   <tag></tag>
   <elementGuidId>638bf957-2ca6-4de6-8628-1e99f5cb0345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-10']/div/div/div/section[2]/section/div/address/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-customer-details--email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;elpapa@cielo.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f1691149-de9d-44cd-9d37-1bcd7e193f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-customer-details--email</value>
      <webElementGuid>1a865bbf-5afa-499c-abe3-adf1d1c1d448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>elpapa@cielo.com</value>
      <webElementGuid>76a52bc4-fed2-4c4b-a7b1-bbf6c4fe44e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-10&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/section[@class=&quot;woocommerce-customer-details&quot;]/section[@class=&quot;woocommerce-columns woocommerce-columns--2 woocommerce-columns--addresses col2-set addresses&quot;]/div[@class=&quot;woocommerce-column woocommerce-column--1 woocommerce-column--billing-address col-1&quot;]/address[1]/p[@class=&quot;woocommerce-customer-details--email&quot;]</value>
      <webElementGuid>ac87daaa-6992-4195-8450-4530651fd22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-10']/div/div/div/section[2]/section/div/address/p[2]</value>
      <webElementGuid>fe3dcd47-a375-49fd-adc6-11b9118d717a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing address'])[1]/following::p[2]</value>
      <webElementGuid>0ca66cbb-078c-48e1-b636-6efd8ee69477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping address'])[1]/preceding::p[1]</value>
      <webElementGuid>51d41102-caaf-4d56-97da-805111b33185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon customerDXC628 Nguyen Hai PhongHCMVietnam'])[1]/preceding::p[1]</value>
      <webElementGuid>12db98c9-5b9d-4e57-9e4b-272b42bbcad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='elpapa@cielo.com']/parent::*</value>
      <webElementGuid>2fa92c41-7b77-4c82-9cc5-9b2fac4f5c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//address/p[2]</value>
      <webElementGuid>2495b98a-5079-41fc-83ad-7959ff231e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'elpapa@cielo.com' or . = 'elpapa@cielo.com')]</value>
      <webElementGuid>6769d708-2fb0-4a22-aeb3-54d9e3fe3a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
