<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingPhoneNumber</name>
   <tag></tag>
   <elementGuidId>46921d6c-7ea2-4b47-836b-80c7072cc4d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-10']/div/div/div/section[2]/section/div/address/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-customer-details--phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0289928289&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cef1da72-0f07-4999-afcb-59ba4c708c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-customer-details--phone</value>
      <webElementGuid>51778780-98b5-4d47-91b2-829712b1c371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0289928289</value>
      <webElementGuid>77aa23b6-0f3d-4adc-b5cf-14af76c6df10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-10&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/section[@class=&quot;woocommerce-customer-details&quot;]/section[@class=&quot;woocommerce-columns woocommerce-columns--2 woocommerce-columns--addresses col2-set addresses&quot;]/div[@class=&quot;woocommerce-column woocommerce-column--1 woocommerce-column--billing-address col-1&quot;]/address[1]/p[@class=&quot;woocommerce-customer-details--phone&quot;]</value>
      <webElementGuid>ed98c7d9-11eb-490b-8e45-dfaf4102a18e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-10']/div/div/div/section[2]/section/div/address/p</value>
      <webElementGuid>51a51952-b6d9-493a-b9a0-90f525d739b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing address'])[1]/following::p[1]</value>
      <webElementGuid>65e41a65-77c5-45eb-8c91-d58b08e8ddb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping address'])[1]/preceding::p[2]</value>
      <webElementGuid>d9255b83-042d-420d-be87-764237dec7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon customerDXC628 Nguyen Hai PhongHCMVietnam'])[1]/preceding::p[2]</value>
      <webElementGuid>9cf8f974-7272-4248-9149-fd52ad5c85c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0289928289']/parent::*</value>
      <webElementGuid>5712ab1a-5dcd-43cc-870b-71234c380797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//address/p</value>
      <webElementGuid>e3ccd896-a9a3-4e2e-951b-18721639f336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0289928289' or . = '0289928289')]</value>
      <webElementGuid>cd9342a1-d399-4ff8-95ce-dca14b6c7faf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
