<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShippingAddressSectionTitle</name>
   <tag></tag>
   <elementGuidId>9e4ac6ef-d65b-4657-9ca0-f1c2d1b2ef7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-10']/div/div/div/section[2]/section/div[2]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-column.woocommerce-column--2.woocommerce-column--shipping-address.col-2 > h2.woocommerce-column__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Shipping address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>25720013-e374-402a-8fe1-331d15826708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-column__title</value>
      <webElementGuid>b8c680bb-5657-4976-a1aa-c20879fe7134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping address</value>
      <webElementGuid>2550a9a4-6089-44e6-b244-313e0c1a64cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-10&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/section[@class=&quot;woocommerce-customer-details&quot;]/section[@class=&quot;woocommerce-columns woocommerce-columns--2 woocommerce-columns--addresses col2-set addresses&quot;]/div[@class=&quot;woocommerce-column woocommerce-column--2 woocommerce-column--shipping-address col-2&quot;]/h2[@class=&quot;woocommerce-column__title&quot;]</value>
      <webElementGuid>c0d92f07-c4d0-445a-9866-eedd0f359d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-10']/div/div/div/section[2]/section/div[2]/h2</value>
      <webElementGuid>596e5aef-e74a-444b-97e0-46f7d4154b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing address'])[1]/following::h2[1]</value>
      <webElementGuid>bc2ce631-b500-402d-9420-54a9e6303621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon customerDXC628 Nguyen Hai PhongHCMVietnam'])[1]/preceding::h2[1]</value>
      <webElementGuid>73370145-0779-4c33-9009-620c78a6f944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/preceding::h2[1]</value>
      <webElementGuid>7c79d5ca-8e97-4327-8fac-cf25a95cb509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipping address']/parent::*</value>
      <webElementGuid>4e92e137-ae0c-449a-88f9-a006cb6f6f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2</value>
      <webElementGuid>002037e8-4b41-4ab6-bf67-ed294163973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Shipping address' or . = 'Shipping address')]</value>
      <webElementGuid>7bfc60bd-e04c-4adf-ad6e-3056bc3199b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
