<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ViewHyperlink</name>
   <tag></tag>
   <elementGuidId>d917e875-69f3-42ca-804a-72a9eb9c6e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-10']/div/div/div/table/tbody/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-button.button.view</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Order: #143505 Date: March 27, 2025 Status: Processing Total: $32.00 for 1 item Actions: View&quot;i] >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d9f6417-1d7c-4c8d-bcf7-3796430953db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/my-account/view-order/143505/</value>
      <webElementGuid>ab88eeb6-67b7-4050-ae0e-baee8a109fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-button button view</value>
      <webElementGuid>4d668054-11ce-434c-a0c6-230dee655aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>29f489ad-c997-4678-8776-8197edc1b06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-10&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/table[@class=&quot;woocommerce-orders-table woocommerce-MyAccount-orders shop_table shop_table_responsive my_account_orders account-orders-table&quot;]/tbody[1]/tr[@class=&quot;woocommerce-orders-table__row woocommerce-orders-table__row--status-processing order&quot;]/td[@class=&quot;woocommerce-orders-table__cell woocommerce-orders-table__cell-order-actions&quot;]/a[@class=&quot;woocommerce-button button view&quot;]</value>
      <webElementGuid>7b95e458-5353-4412-9a55-bd776826f750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-10']/div/div/div/table/tbody/tr/td[5]/a</value>
      <webElementGuid>a7805358-3a88-4193-874d-1e6223c8a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>9f358e9c-af25-4280-99bb-6b89098c6ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::a[1]</value>
      <webElementGuid>19a8d65a-cffe-44de-be86-40fcaaea2a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#143503'])[1]/preceding::a[1]</value>
      <webElementGuid>4f28e2eb-fb3c-4588-b0e2-3ec32698cc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 27, 2025'])[2]/preceding::a[2]</value>
      <webElementGuid>1117887c-b343-49eb-85df-293f127d55c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>64e93621-4cc8-4c78-b0e0-1461027db823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://cms.demo.katalon.com/my-account/view-order/143505/')])[2]</value>
      <webElementGuid>dbe2d1ec-be81-42dc-a2f7-2d34654e3fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>7af2d072-2895-4e2c-b633-59c7ce4ffeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/my-account/view-order/143505/' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>d0b7b085-6fa2-4a2f-acae-b692d8e0f358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
