<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApartmentSuiteUnitInputFieldforDiffAddress</name>
   <tag></tag>
   <elementGuidId>2ae3b256-a160-4ea8-85f3-59757632201e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shipping_address_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shipping_address_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#shipping_address_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03114351-5e0d-4272-8ba8-3adaaa2edfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b3327e6-e0b8-4056-8d92-6bdef2d7e127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>6f5ec9f9-7dcb-4426-a357-3bbc5674519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address_2</value>
      <webElementGuid>05363736-cadf-4e04-a42b-7fd9327bdb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipping_address_2</value>
      <webElementGuid>72251e27-c1f4-4dd7-a0f9-8b95a946e242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit etc. (optional)</value>
      <webElementGuid>ab72f002-9e38-4877-ab57-2a4dc5979269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line2</value>
      <webElementGuid>f241029f-c50e-415c-992b-177d946fa896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit etc. (optional)</value>
      <webElementGuid>e816227c-56ec-439a-9d6e-2b994215dde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping_address_2&quot;)</value>
      <webElementGuid>202a7b51-d852-421f-b87a-773dc05bd8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shipping_address_2']</value>
      <webElementGuid>c511b183-1ba7-4d4a-939b-d91a822b3de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='shipping_address_2_field']/span/input</value>
      <webElementGuid>d080b3c4-5c9c-40d9-8cc2-fb8f1d6f7e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[6]/span/input</value>
      <webElementGuid>e8fbd9bf-382d-462c-a2fa-aee180883db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipping_address_2' and @id = 'shipping_address_2' and @placeholder = 'Apartment, suite, unit etc. (optional)']</value>
      <webElementGuid>91f2c9a5-0341-4ec5-adcc-73e4095e1673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
